sonar.host.url=https://sonar.corp.bankbtpn.co.id

sonar.projectKey=Customer-Administrative-Platform:ekyc-web
sonar.projectName=ekyc-web
sonar.projectVersion=1.0
sonar.login=be19a24a474253634697822a15921bd2230f2474

sonar.language=js
sonar.sources=src
sonar.sourceEncoding=UTF-8

#import the Lcov report
sonar.javascript.lcov.reportPaths=artifacts/coverage/lcov.info

sonar.coverage.exclusions=main.tsx, **/app/ekyc/page.tsx, **/configurations/**, **/tests/**, **/types/**, **/index.css/**, **/App.css/**, **/*.test.tsx, **/src/**