sonar.host.url=https://sonar.corp.bankbtpn.co.id

sonar.projectKey=Customer-Administrative-Platform:ekyc-web
sonar.projectName=ekyc-web
sonar.projectVersion=1.0
sonar.login=be19a24a474253634697822a15921bd2230f2474
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300

sonar.language=js
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.tests=test
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

#import the Lcov report
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.coverage.exclusions=\
  src/**/*.test.ts,\
  src/**/*.test.tsx,\
  src/**/*.spec.ts,\
  src/**/*.spec.tsx,\
  src/**/*.stories.ts,\
  src/**/*.stories.tsx,\
  src/types/**,\
  src/**/*.d.ts,\
  src/**/index.ts,\
  src/components/providers/**,\
  src/app/**/layout.tsx,\

sonar.exclusions=\
  node_modules/**,\
  .next/**,\
  out/**,\
  public/**,\
  coverage/**,\
  **/*.test.ts,\
  **/*.test.tsx,\
  **/*.spec.ts,\
  **/*.spec.tsx,\
  **/*.stories.ts,\
  **/*.stories.tsx,\
  **/*.d.ts,\
  **/types/**,\
  **/mocks/**,\
  **/fixtures/**,\
  next.config.*,\
  tailwind.config.*,\
  postcss.config.*,\
  jest.config.*,\
  jest.setup.*
