import { CustomerInfoData } from '@/types/onboarding';

export const CUSTOMER_INFO_MOCK_DATA: CustomerInfoData = {
  customerType: '31 - Corporate Japanese',
  checklistStatus: 'Pending',
  checklistStage: 'KYCprogress',
  capId: 'CAP-2024-001',
  besReferenceNo: 'BES-998877',
  cifNo: 'CIF12345678',
  customerName: 'SUZUKI MOTOR CORPORATION',
  formerlyKnownAs: '-',
  businessNameAlsoKnownAs: 'SUZUKI MOTOR',
  dateOfEstablishment: '1920-03-15',
  legalEntityType: 'Joint Stock Company',
  legalEntityCharacteristic: 'Publicly Listed',
  lineOfBusiness: 'Automotive Manufacturing',
  registerAddressCountry: 'Japan',
  correspondenceAddressCountry: 'Japan',
  rmRoName: 'Ichiro Tanaka',
  rmRoCode: 'RM001',
  department: 'Corporate Banking',
  finalRiskRating: '---',
  riskScore: '---',
  creationDate: '2024-01-10',
  approvalDate: '-',
  previousChecklistId: 'CHK-2024-0001',
  previousRiskRating: 'Low',
  nextReviewDueDate: '2025-01-10',
  reviewedTo: '---',
  generalChecking: [],
} as const;